name: Push firefox version

on:
  push:
    branches:
      - master
jobs:
  merge-manifests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Commit and push if needed
      run: |
        npm install
        npm run build:chrome
        ls -a

